version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    ports:
      - "8000:8000"
    network_mode: "host"

  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/theswitch"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
    network_mode: "host"

